import Link from "next/link";
import { Icon } from "../components/Icon";

const useCases = [
  { title: "Marketplaces", body: "Keep a stable RecallGuard record beside a marketplace namespace without claiming the marketplace authenticated its facts.", icon: "box" as const },
  { title: "Procurement", body: "Check registered product facts against official recall records before equipment enters a workflow.", icon: "scan" as const },
  { title: "Resellers", body: "Turn append-only recall assessments into a clear operational state for catalog and fulfillment teams.", icon: "activity" as const },
  { title: "Operations", body: "Keep model, lot, and serial context attached to a record that any connected party can challenge.", icon: "shield" as const },
];

export default function LandingPage() {
  return <main className="marketing-page">
    <header className="marketing-header"><Link className="marketing-brand" href="/"><span className="brand-mark">R</span><span><strong>RecallGuard</strong><small>Consensus-backed recall applicability</small></span></Link><nav className="marketing-nav" aria-label="Marketing navigation"><a href="#how-it-works">How it works</a><a href="#trust-boundary">Trust boundary</a><a href="#use-cases">Use cases</a></nav><Link className="button button-dark" href="/app">Open app <Icon name="arrow" size={15} /></Link></header>
    <section className="marketing-hero"><div className="hero-copy"><div className="eyebrow eyebrow-dark"><span className="eyebrow-pulse" />Product safety operations</div><h1>Make recall applicability inspectable.</h1><p>RecallGuard asks one narrow question: do immutable registered product facts fall within an authoritative CPSC recall record, as independently adjudicated by GenLayer validators?</p><div className="hero-actions"><Link className="button button-dark button-large" href="/app">Open RecallGuard <Icon name="arrow" size={17} /></Link><a className="button button-light button-large" href="#how-it-works">See how it works <Icon name="chevron" size={16} /></a></div><div className="hero-proof"><span><Icon name="shield" size={15} />Append-only records</span><span><Icon name="network" size={15} />Independent validators</span><span><Icon name="check" size={15} />Fails closed</span></div></div><div className="hero-visual" aria-label="Illustration of registered product facts moving through a CPSC assessment"><div className="visual-label">Illustrative assessment flow</div><div className="flow-card listing-flow"><div className="flow-card-top"><span className="mini-icon mini-blue"><Icon name="box" size={16} /></span><span className="flow-status">Registered facts</span></div><strong>Hydraulic pump XP-100</strong><small>Model XP-100 · lot LOT-7</small><div className="flow-chip">Identity committed</div></div><div className="flow-line"><span /><span /><span /></div><div className="flow-card recall-flow"><div className="flow-card-top"><span className="mini-icon mini-amber"><Icon name="link" size={16} /></span><span className="flow-status">Official CPSC record</span></div><strong>Recall number 26741</strong><small>Fixed API boundary · canonical facts</small><div className="flow-chip">Authority policy + integrity</div></div><div className="flow-line"><span /><span /><span /></div><div className="flow-card result-flow"><div className="flow-card-top"><span className="mini-icon mini-green"><Icon name="shield" size={16} /></span><span className="flow-status">Consensus result</span></div><strong>Shared safety state</strong><div className="result-options"><span className="result-option option-blocked">Blocked</span><span className="result-option option-review">Review</span><span className="result-option option-clear">Cleared</span></div><small>Only a successful contract record changes state.</small></div></div></section>
    <section className="logo-strip"><span>Built for teams that move products</span><div><strong>MARKETPLACES</strong><strong>PROCUREMENT</strong><strong>RESELLERS</strong><strong>OPERATIONS</strong></div></section>
    <section className="marketing-section split-section" id="how-it-works"><div className="section-lead"><div className="eyebrow eyebrow-dark">A narrow trust question</div><h2>Recall applicability is not a marketplace authenticity claim.</h2><p>RecallGuard does not prove that Amazon or another marketplace displayed the registered facts. It records those facts from a specific address, retrieves an authoritative CPSC record, and stores the consensus-backed applicability outcome.</p><Link className="text-link text-link-dark" href="/app"><span>Explore the workspace</span><Icon name="arrow" size={15} /></Link></div><div className="principle-grid"><Principle number="01" title="Bind the record" body="Identity version, marketplace host, and external listing ID form the stable on-chain key." /><Principle number="02" title="Register facts" body="Product ID, name, manufacturer, model, and lot are immutable facts registered by an address." /><Principle number="03" title="Check CPSC" body="The contract constructs one fixed official API request and canonicalizes only decision-relevant fields." /><Principle number="04" title="Store consequence" body="AFFECTED, INCONCLUSIVE, and NOT_AFFECTED map to append-only state aggregation." /></div></section>
    <section className="marketing-section network-section" id="trust-boundary"><div className="section-heading centered"><div className="eyebrow eyebrow-dark">The trust boundary</div><h2>Each layer says exactly what it proves.</h2><p>Source policy establishes admissibility. Canonicalization binds decision facts. Consensus compares independent derivations. Protocol finality comes from the transaction lifecycle.</p></div><div className="network-diagram"><div className="network-node node-source"><Icon name="link" size={20} /><strong>Official CPSC API</strong><span>Admissible authority</span></div><div className="network-connector" /><div className="network-node node-contract"><Icon name="shield" size={22} /><strong>RecallGuard contract</strong><span>Facts + state history</span></div><div className="network-connector" /><div className="network-node node-validators"><div className="validator-dots"><i /><i /><i /></div><strong>Independent validators</strong><span>Same canonical decision</span></div></div></section>
    <section className="marketing-section use-case-section" id="use-cases"><div className="section-heading"><div><div className="eyebrow eyebrow-dark">Who it is for</div><h2>Make recall review operational.</h2></div><p>One shared state for the people who list, buy, move, and operate products.</p></div><div className="use-case-grid">{useCases.map((item) => <div className="use-case-card" key={item.title}><span className="use-case-icon"><Icon name={item.icon} size={18} /></span><h3>{item.title}</h3><p>{item.body}</p><Icon name="arrow" size={15} /></div>)}</div></section>
    <section className="marketing-section security-section"><div className="security-panel"><div className="security-copy"><div className="eyebrow eyebrow-dark">Designed to fail closed</div><h2>No source. No agreement. No false clearance.</h2><p>Unavailable CPSC data, malformed model output, validator disagreement, and failed execution produce no business verdict and no listing state mutation.</p></div><div className="security-list"><SecurityItem title="Authority is policy" body="CPSC is admitted through an exact host and path boundary; SHA-256 is integrity, not publisher authentication." /><SecurityItem title="Facts are canonical" body="Only decision-relevant CPSC fields are retained in the assessment record; the raw HTTP body is not stored." /><SecurityItem title="Completion is proven" body="The app requires final lifecycle state, FINISHED_WITH_RETURN, and authoritative readback before showing completion." /></div></div></section>
    <section className="final-cta"><div><div className="eyebrow eyebrow-light">Start with one listing</div><h2>Make the next recall decision inspectable.</h2><p>Register facts, invite a permissionless CPSC check, and read the resulting contract state.</p></div><Link className="button button-light button-large" href="/app">Open RecallGuard <Icon name="arrow" size={17} /></Link></section>
    <footer className="marketing-footer"><Link className="marketing-brand" href="/"><span className="brand-mark">R</span><span><strong>RecallGuard</strong><small>Consensus-backed recall applicability</small></span></Link><span>Registered facts · authoritative CPSC scope</span><span>GenLayer Project</span></footer>
  </main>;
}

function Principle({ number, title, body }: { number: string; title: string; body: string }) { return <div className="principle"><span>{number}</span><div><h3>{title}</h3><p>{body}</p></div></div>; }
function SecurityItem({ title, body }: { title: string; body: string }) { return <div className="security-item"><span className="security-check"><Icon name="check" size={14} /></span><div><strong>{title}</strong><p>{body}</p></div></div>; }
