import Link from "next/link";
import { Icon } from "../components/Icon";

const useCases = [
  { title: "Marketplaces", body: "Keep a product's safety state attached to the listing that customers actually see.", icon: "box" as const },
  { title: "Procurement", body: "Check suppliers against official notices before equipment enters an approved workflow.", icon: "scan" as const },
  { title: "Resellers", body: "Turn recall review into a clear operational state across catalog and fulfillment teams.", icon: "activity" as const },
  { title: "Equipment operators", body: "Track lots and models across a fleet without relying on one private database.", icon: "shield" as const },
];

export default function LandingPage() {
  return <main className="marketing-page">
    <header className="marketing-header"><Link className="marketing-brand" href="/"><span className="brand-mark">R</span><span><strong>RecallGuard</strong><small>Decentralized listing safety</small></span></Link><nav className="marketing-nav" aria-label="Marketing navigation"><a href="#how-it-works">How it works</a><a href="#network">Safety network</a><a href="#use-cases">Use cases</a></nav><Link className="button button-dark" href="/app">Open app <Icon name="arrow" size={15} /></Link></header>
    <section className="marketing-hero"><div className="hero-copy"><div className="eyebrow eyebrow-dark"><span className="eyebrow-pulse" />Evidence-bound safety operations</div><h1>Know what should no longer be sold.</h1><p>RecallGuard answers the trust-sensitive question behind every product recall: does this specific listing fall within the affected scope of an authoritative notice?</p><div className="hero-actions"><Link className="button button-dark button-large" href="/app">Open RecallGuard <Icon name="arrow" size={17} /></Link><a className="button button-light button-large" href="#how-it-works">See how it works <Icon name="chevron" size={16} /></a></div><div className="hero-proof"><span><Icon name="shield" size={15} />Contract-owned verdicts</span><span><Icon name="network" size={15} />Independent validators</span><span><Icon name="check" size={15} />Fails closed</span></div></div><div className="hero-visual" aria-label="Illustration of a listing moving through evidence and validator assessment"><div className="visual-label">Illustrative assessment flow</div><div className="flow-card listing-flow"><div className="flow-card-top"><span className="mini-icon mini-blue"><Icon name="box" size={16} /></span><span className="flow-status">Tracked product</span></div><strong>Hydraulic pump XP-100</strong><small>Lot LOT-7 · evidence attached</small><div className="flow-chip">Listing identity committed</div></div><div className="flow-line"><span /><span /><span /></div><div className="flow-card recall-flow"><div className="flow-card-top"><span className="mini-icon mini-amber"><Icon name="link" size={16} /></span><span className="flow-status">Official evidence</span></div><strong>Recall notice 24-118</strong><small>Configured authority · SHA-256 bound</small><div className="flow-chip">Source policy + integrity</div></div><div className="flow-line"><span /><span /><span /></div><div className="flow-card result-flow"><div className="flow-card-top"><span className="mini-icon mini-green"><Icon name="shield" size={16} /></span><span className="flow-status">GenLayer assessment</span></div><strong>Shared safety state</strong><div className="result-options"><span className="result-option option-blocked">Blocked</span><span className="result-option option-review">Review</span><span className="result-option option-clear">Clear</span></div><small>Only the successful contract record is authoritative.</small></div></div></section>
    <section className="logo-strip"><span>Built for teams that move products</span><div><strong>MARKETPLACES</strong><strong>PROCUREMENT</strong><strong>RESELLERS</strong><strong>OPERATIONS</strong></div></section>
    <section className="marketing-section split-section" id="how-it-works"><div className="section-lead"><div className="eyebrow eyebrow-dark">A stronger source of truth</div><h2>Recall applicability is not a keyword search.</h2><p>A listing can be affected by its model, lot, serial range, or product description. RecallGuard makes that semantic decision inside a GenLayer Intelligent Contract, against the evidence that was actually committed for assessment.</p><Link className="text-link text-link-dark" href="/app"><span>Explore the workspace</span><Icon name="arrow" size={15} /></Link></div><div className="principle-grid"><Principle number="01" title="Bind the listing" body="Product identity and public evidence references receive a deterministic on-chain identity." /><Principle number="02" title="Check the source" body="The contract enforces HTTPS, configured authority, availability, bounds, and exact integrity." /><Principle number="03" title="Reach agreement" body="Validators independently reproduce the decision-critical evidence interpretation." /><Principle number="04" title="Store the consequence" body="AFFECTED, INCONCLUSIVE, or NOT_AFFECTED maps to a visible operational state." /></div></section>
    <section className="marketing-section network-section" id="network"><div className="section-heading centered"><div className="eyebrow eyebrow-dark">The safety network</div><h2>Agreement is visible. Evidence stays inspectable.</h2><p>RecallGuard keeps the authority boundary simple: the contract decides; the source policy and integrity checks explain what was admissible; the frontend displays the result.</p></div><div className="network-diagram"><div className="network-node node-source"><Icon name="link" size={20} /><strong>Official source</strong><span>Mutable public notice</span></div><div className="network-connector" /><div className="network-node node-contract"><Icon name="shield" size={22} /><strong>RecallGuard contract</strong><span>Decision + state transition</span></div><div className="network-connector" /><div className="network-node node-validators"><div className="validator-dots"><i /><i /><i /></div><strong>Independent validators</strong><span>Equivalent interpretation</span></div></div></section>
    <section className="marketing-section use-case-section" id="use-cases"><div className="section-heading"><div><div className="eyebrow eyebrow-dark">Who it is for</div><h2>Make recall review operational.</h2></div><p>One shared safety state for the people who list, buy, move, and operate products.</p></div><div className="use-case-grid">{useCases.map((item) => <div className="use-case-card" key={item.title}><span className="use-case-icon"><Icon name={item.icon} size={18} /></span><h3>{item.title}</h3><p>{item.body}</p><Icon name="arrow" size={15} /></div>)}</div></section>
    <section className="marketing-section security-section"><div className="security-panel"><div className="security-copy"><div className="eyebrow eyebrow-dark">Designed to fail closed</div><h2>No source. No agreement. No “safe.”</h2><p>Evidence failure, malformed model output, validator disagreement, and failed execution stay in their own error domains. They never become a NOT_AFFECTED verdict.</p></div><div className="security-list"><SecurityItem title="Evidence authenticity" body="Domain policy is deterministic and separate from consensus." /><SecurityItem title="Evidence integrity" body="The contract checks the exact SHA-256 commitment." /><SecurityItem title="Transaction integrity" body="A hash or finality alone is never shown as success." /></div></div></section>
    <section className="final-cta"><div><div className="eyebrow eyebrow-light">Start with one listing</div><h2>Make the next recall decision inspectable.</h2><p>Register a product, attach its public evidence, and let the contract own the safety state.</p></div><Link className="button button-light button-large" href="/app">Open RecallGuard <Icon name="arrow" size={17} /></Link></section>
    <footer className="marketing-footer"><Link className="marketing-brand" href="/"><span className="brand-mark">R</span><span><strong>RecallGuard</strong><small>Decentralized listing safety</small></span></Link><span>Evidence-bound product recall applicability</span><span>GenLayer Project</span></footer>
  </main>;
}

function Principle({ number, title, body }: { number: string; title: string; body: string }) {
  return <div className="principle"><span>{number}</span><div><h3>{title}</h3><p>{body}</p></div></div>;
}

function SecurityItem({ title, body }: { title: string; body: string }) {
  return <div className="security-item"><span className="security-check"><Icon name="check" size={14} /></span><div><strong>{title}</strong><p>{body}</p></div></div>;
}
